apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: userlist
  namespace: userlist
spec:
  gateways:
  - userlist-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /usuario
      method:
        exact: GET
    rewrite:
      uri: /usuario
    route:
    - destination:
        host: userlist
        port:
          number: 8080